apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpp-bot-auth-pvc
  namespace: wpp-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: linode-block-storage-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpp-bot-cache-pvc
  namespace: wpp-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: linode-block-storage
