apiVersion: v1
kind: Service
metadata:
  name: wpp-bot
  namespace: wpp-bot
  labels:
    app: wpp-bot
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: wpp-bot
