apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wpp-bot-ingress
  namespace: wpp-bot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - boteco.solvelabs.dev
        - api.boteco.solvelabs.dev
        - dashboard.boteco.solvelabs.dev
      secretName: wpp-bot-tls
  rules:
    - host: boteco.solvelabs.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wpp-landing
                port:
                  number: 80
    - host: api.boteco.solvelabs.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wpp-bot
                port:
                  number: 3000
    - host: dashboard.boteco.solvelabs.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wpp-dashboard
                port:
                  number: 80
