apiVersion: v1
kind: Service
metadata:
  name: wpp-landing
  namespace: wpp-bot
  labels:
    app: wpp-landing
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: wpp-landing
